import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@user.com',
      password: bcrypt.hashSync('123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Ryzen 7 5800x',
      slug: 'ryzen-7-5800x',
      category: 'CPU',
      image: '/Images/ryzen7.jpg',
      price: 300,
      countInStock: 5,
      brand: 'AMD',
      rating: 4.8,
      numReviews: 3,
      description: '4.7Ghz, 105W TDP, 8 cores, 16 threads',
    },
    {
      name: 'Ryzen 5 5600x',
      slug: 'ryzen-5-5600x',
      category: 'CPU',
      image: '/Images/ryzen5.jpg',
      price: 300,
      countInStock: 2,
      brand: 'AMD',
      rating: 4.3,
      numReviews: 1,
      description: '4.6Ghz, 65W TDP, 6 cores, 12 threads',
    },
    {
      name: 'Ryzen 5 5500',
      slug: 'ryzen-5-5500',
      category: 'CPU',
      image: '/Images/ryzen5.jpg',
      price: 210,
      countInStock: 1,
      brand: 'AMD',
      rating: 4.9,
      numReviews: 5,
      description: '4.2Ghz, 65W TDP, 6 cores, 12 threads',
    },
    {
      name: 'Ryzen 5 5600G',
      slug: 'ryzen-5-5600g',
      category: 'CPU',
      image: '/Images/ryzen5.jpg',
      price: 180,
      countInStock: 2,
      brand: 'AMD',
      rating: 5.0,
      numReviews: 2,
      description: '4.4Ghz, 65W TDP, 6 cores, 12 threads',
    },
    {
      name: 'NVIDIA RTX 3050',
      slug: 'nvidia-rtx-3050',
      category: 'GPU',
      image: '/Images/rtx3050.png',
      price: 360,
      countInStock: 2,
      brand: 'NVIDIA',
      rating: 4.5,
      numReviews: 7,
      description:
        'PCIe 4.0 x8, 8GB VRAM, 1830Mhz boost, 1xHDMI 2.1, 3xDP 1.4a, 1x8pin power connector',
    },
    {
      name: 'AMD RX 6600',
      slug: 'amd-rx-6600',
      category: 'GPU',
      image: '/Images/rx6600.jpg',
      price: 420,
      countInStock: 3,
      brand: 'AMD',
      rating: 4.7,
      numReviews: 9,
      description:
        'PCIe 4.0 x8, 8GB VRAM, 2401Mhz boost, 1xHDMI 2.1, 3xDP 1.4, 1x8pin power connector',
    },
    {
      name: 'NVIDIA RTX 3090',
      slug: 'nvidia-rtx-3090',
      category: 'GPU',
      image: '/Images/rtx3090.jpg',
      price: 2750,
      countInStock: 1,
      brand: 'NVIDIA',
      rating: 5.0,
      numReviews: 1,
      description:
        'PCIe 4.0 x16, 24GB VRAM,10496 CUDA Cores, 1890Mhz boost, 2xHDMI 2.1, 3xDP 1.4a, 3x8pin power connectors',
    },
  ],
};
export default data;
